name: Run Script

on:
  push:
    branches: 
  pull_request:
    branches: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            os.chdir("Recipes")
            
            def read_script(f,scriptname,tab=0,childextension=".rcp"):
              script = open(scriptname,"r")
              tab = tab +1
              for child in script.readlines():
                child=child.strip()
                if len(child) > 0 and child[0] != "#" and not child.startswith("DATE") and not child.startswith("AUTHOR") and not child.startswith("DESCRIPTION"):
                  f.write((f"{tab*6*'-'}>  {child.split('#')[0]}\n"))
                  try:
                    read_script(f,child,tab)
                  except:
                    pass
              script.close()

            f = open("daily.summary","w")
            f.write("daily.menu\n")
            read_script(f,"daily.menu",0,".cbk")
            f.close()
      - uses: actions/upload-artifact@v2
        with:
          name: daily.summary
          path: Recipes/daily.summary
          
      - uses: actions/download-artifact@v2
        with:
          name: daily.sum2
          path: Recipes/daily.summary2
      
